<div class="formulario">
   <div class="menu_adm_rapido">
       <div id="top">
           <div id="left"></div>
           <div id="right"></div>
       </div>
       <div id="center">
           <div id="texto_controller"><strong>Opçoes rápidas</strong><br/><span>Ofertas</span></div>
            <ul>
                <li><a href="/loja_ofertas/add" title="Cadastrar Ofertas"><span id="icon-32-new"></span> Cadastrar Ofertas </a></li>
                <li><a href="/loja_ofertas/index" title="Listar Ofertas"><span id="icon-32-archive"></span> Listar Ofertas </a></li>
            </ul>
        </div>
    </div>

    <h3>Listar categorias</h3>
    <?php echo $this->flashMessage ?>
    <div id="bread_crumb_count">Foram encontrada <?php echo $ofertas['total_found'] ?> categorias.</div>
    
    <table id="result" border="0px" cellspacing="0px"  style="width: 100%">
        <tbody>
            <th>Nome</th>
            <th>Descricao</th>
            <th width="30px;">Preco</th>
            <th width="70px;">Status</th>
            <th width="65px;">Ações</th>
            <?php 
                if(isset($ofertas['total_found'])){
                    $quantidade = $ofertas['total_found'];
                    unset($ofertas['total_found']);
                }
            ?>
            <?php foreach($ofertas as $oferta):?>
            <tr>
                <td><?php echo $oferta['titulo'] ?></td>
                <td><?php echo $oferta['descricao'] ?></td>
                <td><?php echo $oferta['preço'] ?></td>
                <td><?php if($oferta['ativo'] == 1) $class = 'status_ativo'; else $class = 'status_desativado' ?>
                    <a href="<?php echo "/loja_ofertas/ativar&id=".$oferta['id'].'&status='.$class; ?>" onclick="return confirmAction('Deseja modificar o status deste produto?')">
                    <div id="status" class="<?php echo $class ?>"></div>
                    </a>
                </td>
                <td>
                    <a title="Editar" href="<?php echo '/loja_ofertas/edit&id='.$oferta['id'] ?>"><div class="action_edit"></div></a>
                    <a href="<?php echo "/loja_ofertas/delete&id=".$oferta['id']; ?>" onclick="return confirmAction('Deseja excluir este produto?');">
                    <div id="status" class="action_delete"></div>
                    </a>
                </td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
    <?php echo $this->element('paginacao',array('quantidade'=>$quantidade,'limit'=>$limit,'url'=>'/usuarios/index'));  ?>
</div>

