<script>
    jQuery(function() {
            $( "#accordion" ).accordion();
    });
</script>

<div id="options_fast">
    <div>
        <ul class="menu_adm">
            <li><a href="categorias/add"> <img src="/webroot/img/adm/icon-48-categoria.png"><span>Adicionar Nova Categoria</span></a></li>
            <li><a href="#"> <img src="/webroot/img/adm/icon-48-produtos.png"><span>Adicionar Produtos</span></a></li>
            <li><a href="#"> <img src="/webroot/img/adm/icon-48-pedidos.gif"><span>Ultimos Pedidos</span></a></li>
            <li><a href="/usuarios/index"> <img src="/webroot/img/adm/icon-48-usuarios.png"><span>Gerênciar Usuários</span></a></li>
            <li><a href="#"> <img src="/webroot/img/adm/icon-48-media.png"><span>Gerenciar Mídias</span></a></li>
            <li><a href="#"> <img src="/webroot/img/adm/icon-48-textos.png"><span>Gerênciar Textos</span></a></li>
            <li><a href="#"> <img src="/webroot/img/adm/icon-48-menu.png"><span>Gerênciar Menus</span></a></li>
        </ul>
    </div>
</div>
<div id="notice_fast">
    <div id="accordion">
	<h3><a href="#">Ultimos pedidos</a></h3>
	<div>
		<p>
		Mauris mauris ante, blandit et, ultrices a, suscipit eget, quam. Integer
		ut neque. Vivamus nisi metus, molestie vel, gravida in, condimentum sit
		amet, nunc. Nam a nibh. Donec suscipit eros. Nam mi. Proin viverra leo ut
		odio. Curabitur malesuada. Vestibulum a velit eu ante scelerisque vulputate.
		</p>
	</div>
	<h3><a href="#">Alertas de Produtos</a></h3>
	<div>
		<p>
		 <?php $this->element('alertaproduto',array('produtos_minimo' => $produtos_minimo)); ?>
		</p>
	</div>
	<h3><a href="#">Ultimos clientes cadastrados</a></h3>
	<div>
		<p>
		Nam enim risus, molestie et, porta ac, aliquam ac, risus. Quisque lobortis.
		Phasellus pellentesque purus in massa. Aenean in pede. Phasellus ac libero
		ac tellus pellentesque semper. Sed ac felis. Sed commodo, magna quis
		lacinia ornare, quam ante aliquam nisi, eu iaculis leo purus venenatis dui.
		</p>
		<ul>
			<li>List item one</li>
			<li>List item two</li>
			<li>List item three</li>
		</ul>
	</div>
	<h3><a href="#">Visitas</a></h3>
	<div>
		<p>
		Cras dictum. Pellentesque habitant morbi tristique senectus et netus
		et malesuada fames ac turpis egestas. Vestibulum ante ipsum primis in
		faucibus orci luctus et ultrices posuere cubilia Curae; Aenean lacinia
		mauris vel est.
		</p>
		<p>
		Suspendisse eu nisl. Nullam ut libero. Integer dignissim consequat lectus.
		Class aptent taciti sociosqu ad litora torquent per conubia nostra, per
		inceptos himenaeos.
		</p>
	</div>
</div>
</div>