<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=8" />
        <link href="/webroot/css/jquery.jqzoom.css" rel="stylesheet" type="text/css" />
        <link href="/webroot/css/front.css" rel="stylesheet" type="text/css" />
        <link href="/webroot/css/jquery/jquery.css" rel="stylesheet" type="text/css" />
        <script type="text/javascript" src="/webroot/js/jquery.js"></script>
        <script type="text/javascript" src="/webroot/js/jquery.jqzoom-core-pack.js"></script>
        <script type="text/javascript" src="/webroot/js/jquery-ui.js"></script>
        <script type="text/javascript" src="/webroot/js/adm.js"></script>
        <title>Loja Demo</title>
    </head>
    <body>
    <div id="menu_superior">
        <div>
            <div id="logo">
            <img src="logoo.3.png"/>
            
            <div id="phone">
                <span>Tire suas dúvidas</span><br/>
                <strong>(14)9125-9607</strong>
            </div>
            <ul id="menu_list">
            <li>Bem vindo, faça seu <span>login</span> ou <span> cadastre-se </span></li>
            <li class="separator">Central de atendimento</li>
            <li class="separator">Meu Carrinho <a href="/carrinhos/ver">(ver)</a>
                <span id="info_carrinho"><b><?php if(isset($_SESSION['carrinho'])) echo count($_SESSION['carrinho']); else echo 0 ?></b> Itens</span>
            </li>
            </ul>
            </div>
        </div>
        <div id="spabusca">
            <div id="btn_busca"><span>Busca</span></div>
            <input name="busca" type="text"/>
                
        </div>
    </div>

    <?php
        $categoria = new Categoria();
        $lista_categoria = $categoria->categoriaMenu();
    ?>
        
    <div><?php echo $this->element('menu_marcas',array('lista_categoria'=>$lista_categoria));?></div>

    <div id="conteudo">
        <div id="menu_front">
            <ul>
                <li><strong>Categorias</strong>
                    <ul class="menu_animate">
                    <?php foreach($lista_categoria as $k=>$categoria): ?>
                        <li class="father">
                            <a href="/categorias/listar/&id=<?php echo $categoria['id'] ?>"><span><?php echo $categoria['nome'] ?></span></a>
                        </li>
                            <ul style="margin-left: -40px">
                            <?php foreach( $categoria['filhas'] as $key => $filha): ?>
                                <li class="sub"><a href="/categorias/listar/&id=<?php echo $key ?>"><span><?php echo $filha ?></span></a></li>
                            <?php endforeach; ?>
                            </ul>

                    <?php endforeach; ?>
                    </ul>
                </li>
            </ul>
        </div>
        <div id="display">
           <?php  require_once($require_for_layout);?>
        </div>
    </div>

    <div id="footer">
        <div id="pagamento">
            <img src="/webroot/img/icons/pagamento.gif"/>
        </div>
        <div id="direitos">
            <p>Copyright © 2011 - 2011  TODOS OS DIREITOS RESERVADOS.</p>
            <p>José Henrique Honjoya | José Renato Beltrani</p>
        </div>
    </div>
    </body>
</html>