<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=8" />
        <link href="/webroot/css/front.css" rel="stylesheet" type="text/css" />
        <link href="/webroot/css/jquery/jquery.css" rel="stylesheet" type="text/css" />
        <script type="text/javascript" src="/webroot/js/jquery.js"></script>
        <script type="text/javascript" src="/webroot/js/jquery-ui.js"></script>
        <script type="text/javascript" src="/webroot/js/adm.js"></script>
        <title>Loja Demo</title>
    </head>
    <body>
    <div id="menu_superior">
        <div>
            <div id="phone">
                <span>Tire suas dúvidas</span><br/>
                <strong>(14)9125-9607</strong>
            </div>
            <ul id="menu_list">
            <li>Bem vindo, faça seu <span>login</span> ou <span> cadastre-se </span></li>
            <li class="separator">Central de atendimento</li>
            <li class="separator">Meu Carrinho</li>
            </ul>
            
        </div>
        <div id="spabusca">
            <div id="btn_busca"><span>Busca</span></div>
            <input name="busca" type="text"/>
                
        </div>
    </div>
    <div><?php echo $this->element('menu_marcas');?></div>

    <div id="conteudo">
           <?php  require_once($require_for_layout);?>
    </div>

    <div id="footer">

        <div id="pagamento">
            <img src="/webroot/img/icons/pagamento.gif"/>
        </div>
        <div id="direitos">
            <p>Copyright © 2011 - 2011  TODOS OS DIREITOS RESERVADOS.</p>
            <p>José Henrique Honjoya | José Renato Beltrani</p>
        </div>

    </div>
        
    </body>
</html>