<script>
   function validaCampo(){
     var count = 0

     jQuery("#msg_error").html("");

     jQuery("input").each(function(){
       if(jQuery(this).val() == ''){
          if(count <= 0){
            jQuery("#msg_error").append("<p>Existem campos vazios, favor verificar.</p>");
          }
          count++;
       }
    });

    if(count > 0){
        return false;
    }
    }
</script>

<div class="formulario">
    <div class="menu_adm_rapido">
       <div id="top">
           <div id="left"></div>
           <div id="right"></div>
       </div>
       <div id="center">
           <div id="texto_controller"><strong>Opçoes rápidas</strong><br/><span>Categorias</span></div>
            <ul>
                <li><a href="/categorias/add" title="Cadastrar Categoria"><span id="icon-32-new"></span> Cadastrar Categoria </a></li>
                <li><a href="/categorias/index" title="Listar Categoria"><span id="icon-32-archive"></span> Listar Categproas </a></li>
            </ul>
        </div>
    </div>

    <h3>Editar categorias</h3>
    <div id="box1">
        <form name="form_cadastro_categoria" action="/categorias/edit" method="post">
         <table style="font-size: 13px; font-family: arial">
            <tr>
                <td>Categoria Pai:</td>
                <td>
                    <select id="parent_id" name="parent_id">
                        <option  value="0"> - </option>
                        <?php foreach($categorias_lista as $k => $categ){
                            if(!is_array($categ)){
                                echo '<option value=\''.$k.'\'>'.htmlspecialchars_decode($categ).'</option>';
                            }else{
                                echo '<option '.$categ[1].' value=\''.$k.'\'>'.htmlspecialchars_decode($categ[0]).'</option>';
                            }
                        }
                        ?>
                    </select>

                </td>
            </tr>
            <tr>
                <td>Nome da Categorias:</td>
                <td>
                    <input id="id" name="id" type="hidden" value="<?php echo $categoria['id'] ?>"/>
                   <input id="nome" name="nome" value="<?php echo $categoria['nome'] ?>"/>
                </td>
            </tr>
            <tr>
                <td>Descrição:</td>
                <td><input id="descricao" name="descricao" value="<?php echo $categoria['descricao'] ?>"/></td>
            </tr>
             <tr>
                <td>Ativo:</td>
                <td>

                    <select id="ativo" name="ativo">
                        <option value="1" <?php if($categoria['ativo'] == 1) echo 'selected'; ?>>Ativado</option>
                        <option value="0" <?php if($categoria['ativo'] == 0) echo 'selected'; ?>>Desativado</option>
                    </select>
                </td>
            </tr>
            <tr>
                <td colspan="2"><input class="button_form" type="submit" value="Atualizar" onclick="return validaCampo('Deseja excluir a categoria?');"/></td>
            </tr>
        </table>
        </form>
        <div id="msg_error">

        </div>
    </div>
    <div id="box2">
        <p><strong style="color: red">Página de Cadastrado de categorias para a sua loja.</strong></p>
           <p>Todas as categorias aqui insiridas, aparecerão na página de cadasto de produtos.<br/>
              Categorias com status definido como <strong>Inativa</strong>, não serão exibidas na sua loja.
           </p>
          <?php echo $this->flashMessage;?>
    </div>
</div>