<script style="text\javascript">
	jQuery(document).ready(function(){
            jQuery(".principal").hover(function(){
		jQuery(this).children().eq(1).slideDown();
		},
            function(){
            		jQuery(this).children().eq(1).hide();

		})
            })
</script>

<ul class="menu_top">
    <?php foreach($lista_categoria as $k=>$categ): ?>
    <li class="principal"><a href="/categorias/listar/&id=<?php echo $categ['id'] ?>"><strong><?php echo $categ['nome'] ?></a></strong>
        <ul class="sub_principal">
            <li>
                <ul>
                    <?php foreach($categ['filhas'] as $id => $cate): ?>
                    <li>
                        <a href="/categorias/listar/&id=<?php echo $id ?>"> <?php echo $cate ?> </a>
                    </li>
                    <?php endforeach; ?>
                </ul>
                <div class="content">
                        
                 </div>
            </li>
        </ul>
     <?php endforeach ;?>
</li>
</ul>
<div>
</div>
