<script>
   function validaCampo(){
     var count = 0

     jQuery("#msg_error").html("");

     jQuery("input").each(function(){
       if(jQuery(this).val() == ''){
          if(count <= 0){
            jQuery("#msg_error").append("<p>Existem campos vazios, favor verificar.</p>");
          }
          count++;
       }
    });

    if(count > 0){
        return false;
    }
    }
</script>


<div class="formulario">

    <div class="menu_adm_rapido">
       <div id="top">
           <div id="left"></div>
           <div id="right"></div>
       </div>
       <div id="center">
           <div id="texto_controller"><strong>Opçoes rápidas</strong><br/><span>Usuários</span></div>
            <ul>
                <li><a href="/usuarios/add" title="Cadastrar Usuário"><span id="icon-32-new"></span> Cadastrar Usuários </a></li>
                <li><a href="/usuarios/index" title="Listar Usuário"><span id="icon-32-archive"></span> Listar Usuários </a></li>
            </ul>
        </div>
    </div>

    <h3>Cadastro de Usuarios</h3>
    <div id="box1">
        <form name="form_cadastro_usuarios" action="/usuarios/edit" method="post">
         <table style="font-size: 13px; font-family: arial">
            <tr>
                <td>Grupo:</td>
                <td>
                    <select id="loja_grupo_id" name="loja_grupo_id" >
                        <?php foreach($grupo_lista as $k => $grupo){
                            if(isset($grupo['selected'])) $selected = 'selected'; else $selected = '';
                            echo '<option  value=\''.$grupo['id'].'\' '.$selected.'>'.htmlspecialchars_decode($grupo['grupo']).'</option>';
                        }
                        ?>
                    </select>
                </td>
            </tr>
            <tr>
                <td>Nome do usuário:</td>
                <td>
                    <input id="id" name="id" type="hidden" value="<?php echo $usuario['id'] ?>"/>
                    <input id="usuario" name="usuario" value="<?php echo $usuario['usuario'] ?>"/>
                </td>
            </tr>
            <tr>
                <td>Nome completo:</td>
                <td><input id="nome_completo" name="nome_completo" size="58" value="<?php echo $usuario['nome_completo'] ?>"/></td>
            </tr>
             <tr>
                <td>Ativo:</td>
                <td>
                    <?php  ?>
                    <select id="ativo" name="ativo">
                        <option value="1" <?php if($usuario['ativo'] == 1) echo 'selected' ?>  >Ativado</option>
                        <option value="0" <?php if($usuario['ativo'] == 0) echo 'selected' ?> >Desativado</option>
                    </select>
                </td>
            </tr>
            <tr>
                <td colspan="2"><input class="button_form" type="submit" value="Atualizar" onclick="return validaCampo('Deseja excluir a categoria?');"/></td>
            </tr>
        </table>
        </form>
        <div id="msg_error">

        </div>
    </div>
    <div id="box2">
        <div id="msg_error"></div>
        <p><strong>&nbsp;&nbsp;Cadastro de usuário</strong>, permite que você adicione vários usuários conforme a
         necessidade do seu sistema. Cada usuário cadastrado pertencerá a um grupo de acesso, onde será
         fornecido acesso conforme deliberação do administrador.
        </p>
       <?php echo $this->flashMessage;?>
    </div>
</div>