<script>
   function validaCampo(){
     var count = 0

     jQuery("#msg_error").html("");

     jQuery("input").each(function(){
       if(jQuery(this).val() == ''){
          if(count <= 0){
            jQuery("#msg_error").append("<p>Existem campos vazios, favor verificar.</p>");
          }
          count++;
       }
    });

    if(count > 0){
        return false;
    }
    }
</script>
<div class="formulario">
    <h3>Tipos de Enderecos</h3>
    <div id="box1">
        <form name="form_tipo_enderecos" action="/tipo_enderecos/index" method="post">
        <table>
            <tr>
                <td>texto:</td>
                <td><input id="tipo" name="tipo"/></td>
            </tr>
            <tr>
            <td>Ativo:</td>
                <td>
                    <select id="ativo" name="ativo">
                        <option value="1">Ativado</option>
                        <option value="0">Desativado</option>
                    </select>
                </td>
            </tr>
            <tr>
                <td colspan="2"><input class="button_form" type="submit" value="Cadastrar" onclick="return validaCampo();"/></td>
            </tr>
        </table>
        </form>
        <div id="msg_error">

        </div>
    </div>
</div>